spring.application.name=ECom-proj


spring.datasource.url=jdbc:h2:mem:ecomDB
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.show-sql=true 

#Data initialization is set to true because if we dont then table hi create nahi kar paogay aap
spring.jpa.defer-datasource-initialization=true

